#-------------------------------
# Site Settings
title: Max Heil
logo: "/images/Aerospace Engineer.svg" # You can add own logo. For example '/images/logo.png'.
logo_dark: "/images/Aerospace Engineer_Dark_Mode.svg"
description: Personal website and portfolio for Max Heil
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Elements'
      url: '/elements/'


# Call to action button
cta_button:
  enable: true
  cta_button_link: "/contact/"
  cta_button_text: Say Hello!


#-------------------------------
# Author Settings
author:
  author_intro: Hey, I’m Max Heil
  author_name: Max Heil
  author_role: Aerospace Engineer
  author_avatar: /images/heil.115_headshot_Sept2024_cropped.png


#-------------------------------
# Sidebar Section Settings
sidebar:
  sidebar_title: Welcome! <em>Space Enthusiast,</em> <em>Engineer,</em> <em>Adventurer</em>. # You can add an 'em' element to highlight text.
  sidebar_description: Welcome to my page! Here you'll find engaging facts about my research, work, and life. Please feel free to contact me if you have any questions!


# Social Links
social:
- {icon: "fa-brands fa-linkedin", name: "Linkedin", link: "https://www.linkedin.com/in/max-heil/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/maxheil5"}
- {icon: "fa-brands fa-youtube", name: "Vimeo", link: "https://www.youtube.com/@MaxHeil5"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Projects Settings
projects:
  enable: true
  projects_title: Project <em>Showcase</em> # You can add an 'em' element to highlight text.
  projects_description: I present my top-tier projects, ranging from space systems to mechanical design and 3D printing. I update these projects often, so check back for new information!


#-------------------------------
# Career Settings (called testimonials in all settings)
testimonials:
  enable: true
  testimonials_title: My Career <em>Timeline</em> # You can add an 'em' element to highlight text.
  testimonials_description: Learn about my journey as an aerospace engineer from college and beyond.

testimonial-items:
  - name: The Ohio State University
    image: "/images/Ohio_State_Big_O.jpg"
    designation : Undergraduate, August 2021 - May 2025
    content : Graduated from Ohio State in May 2025 with a Bachelor of Science in Aerospace Engineering with Honors Research Distinction

  - name: Collins Aerospace
    image: "/images/Collins-Aerospace-Logo_Circular.png"
    designation : Advanced Manufacturing Engineering Intern, May 2024 - Jan 2025
    content : Developed automated manufacturing simulations, optimized metal 3D printing processes, validated RFID tracking systems, and contributed to a $3M automation initiative.

  - name: SOAR Laboaratory
    image: "/images/SOAR_Logo.png"
    designation : Controls Undergraduate Researcher, Sept 2023 - Present
    content : Designed data-driven UAV control algorithms, investigated the effects of dither quantization in constrained environments, and conduct drone flight tests.

  - name: LADDCS Laboratory
    image: "/images/Ohio_State_Big_O.jpg"
    designation : Space Systems Graduate Researcher, June 2024 - Present
    content : Analyzed and categorized unknown spacecraft maneuvers using probability & game theory, and implemented Adaptive Monte Carlo techniques for accurate manuever detection.


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Latest <em>News</em> & <em>Activity</em> # You can add an 'em' element to highlight text.
  blog_description: Discover the latest updates to my work and important activities I'm a part of.


#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: true
  faq_title: Questions? <em>Answers</em>. # You can add an 'em' element to highlight text.
  faq_description: Answers to some common questions that I receive.

faq_items:
  - title: What are your main areas of expertise in the aerospace industry?
    description: My specializations includes space systems, quadrotors, orbital mechanics, and propulsion.

  - title: Can you provide examples of your work (i.e. a portfolio)?
    description: Yes! On this website, navigate to the "Projects" tab. There, you will see the various works I collaborate on. Included are both team and individual initiatives with my personal contributions highlighted in each.

  - title: What is your experience with various softwares, coding, or platforms?
    description: I have strong technical proficiency across engineering software, programming languages, and simulation platforms. Software: MATLAB, Simulink, SolidWorks, Ansys Fluid/STK, LabVIEW, XFLR5, Altium, Microsoft Office, Visual Components; Coding: Python, MATLAB, LaTeX, ROS

  - title: Do you have any certifications?
    description: I have the following certifications and am currently working on more: Ansys Systems Tool Kit (STK) Level 1 Certified (Oct 2024), Private Pilot Certificate (Jan 2024), Microsoft Office Specialist (Jan 2018)

  - title: Are you taking 3D print requests right now?
    description: Absolutely! Please reach out to me via email and I will see what I can do.

  - title: How can I contact you to discuss anything?
    description: You can contact me through the contact form on my website or directly via email. I'm always open to new projects and career opportunities, so please reach out!


#-------------------------------
# Gallery Settings
gallery:
  enable: false
  gallery_title: A Visual Journey Through <em>My World</em> # You can add an 'em' element to highlight text.
  gallery_description: Step into my visual world where each image tells a story. From the bustling streets of urban landscapes to the serene beauty of nature, explore the moments that inspire and define my journey.
  gallery_caption:

gallery_images:
  - alt: 'Together'
    url: '/images/100.jpg'
  - alt: 'Lifestyle'
    url: '/images/101.jpg'
  - alt: 'Friends'
    url: '/images/102.jpg'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Subscribe to My <em>Newsletter</em> # You can add an 'em' element to highlight text.
  mailchimp_description: Subscribe to my newsletter and get notified when I have a new project or update.
  mailchimp_identifier: osu.us12.list-manage.com/subscribe/post?u=5bb5f73dc05873f953e68b168&amp;id=12e91b9ec0&amp;f_id=00e578e1f0 # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: Baleon comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Baleon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
